.github/pr-labeler.yml
.github/workflows/pr-labeler.yml
.github/workflows/sync-with-generics-repository.yml
.github/workflows/syntax-ansible.yml
.github/workflows/syntax-yaml.yml
.github/yamllint.yml
.information.yml
.travis.yml
gilt.yml

Drop versions < 1.4.0 & sync with generics

---

.travis.yml

Add version 1.4.3

---

.travis.yml

Add version 1.5.1

---

.travis.yml

Add versions 1.5.2 & 1.5.3

---

Dockerfile

Resolve "Avoid use of cache directory with pip" issue

---

.github/workflows/build-docker-image.yml

Add version 1.5.4

---

files/run.sh

Make number of workers configurable

---

.github/renovate.json
Dockerfile
files/requirements.txt

Pin requirements

---

Dockerfile
files/requirements.txt
files/run.sh

Make worker class configurable

---

files/run.sh

Add missing ARA_

---

.github/workflows/build-docker-image.yml

Add version 1.5.5

---

.github/workflows/build-docker-image.yml

Add version 1.5.6 & remove version 1.5.3

---

README.md

Fix the title in the README file

---

.github/workflows/build-docker-image.yml

github: only build the latest stable version

---

Containerfile

Install curl (missing in pypy base image)

---

Containerfile

Use a multi stage build

---

Containerfile

Install ARA as a wheel

---

Containerfile

Move curl package

---

Containerfile

Create wheels directory

---

.github/workflows/build-docker-image.yml

Use version 1.5.7

---

.github/workflows/build-docker-image.yml

github: build docker image on self-hosted runner

---

.github/workflows/build-container-image.yml
Containerfile

Add missing runs-on & env variables & use libmariadb-dev
